version: "3"

x-service-config: &service-config
  environment:
    IS_DEPLOYED: ${IS_DEPLOYED:-true}
    IS_DEBUG: ${IN_DEBUG:-true}
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-default-unsafe-secret-key}
    ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
    CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://localhost:8080,http://127.0.0.1:8080,http://0.0.0.0:8080}
    POSTGRES_DB: ${POSTGRES_DB:-securities_firm}
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_HOST: ${POSTGRES_HOST:-db}
    POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    APP_NAME: ${APP_NAME:-securities_firm}
    UVICORN_WORKER_NUMS: ${UVICORN_WORKER_NUMS:-1}
    UVICORN_DEBUG_RELOAD: ${UVICORN_DEBUG_RELOAD:-true}


services:
  app:
    <<: *service-config
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    image: securities_firm:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-securities_firm}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB",
        ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
