# Generated by Django 5.2.4 on 2025-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
